name: C_C++_CI with dev

on:
  pull_request:
    branches:
      - dev

jobs:
  build-with-gcc:
    uses: NWChemEx-CI-test/.github/.github/workflows/image-c-cpp_tmpl.yaml@master
    with: 
      repo: PluginPlay
      clang-build: false
      gcc-build: true
      ninja_build: true
      test: true
      integration_test: false
      install: false
    secrets: inherit
            #CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
            #DOCKER_PAT: {{ secrets.DOCKER_PAT }}
