name: Test of receiving a repo dispatch
on:
  repository_dispatch:
    types: [utilities_release_update, parallelzone_release_update]

jobs:
  repo_dispatch_test:
    runs-on: ubuntu-latest
    steps:
      - name: Receive a repo dispatch
        run: |
             echo "Dispatch from the Utilities repo received!"
